# Generated by Django 3.1.4 on 2020-12-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201209_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
